% 班级：16171046，姓名：谢思涵
function M22
    %构建所有组件
    f = figure( ...
        'Name', 'Simple GUI', ...
        'Visible', 'off', ...
        'Position', [0, 0, 450, 285] ...
    ); %窗口
    hsurf    = uicontrol( ...
        'Style', 'pushbutton', ...
        'String', 'Surf', ...
        'Position', [315, 220, 70, 25], ...
        'Callback', @surfbutton_Callback ...
    ); %surf按钮
    hmesh    = uicontrol( ...
        'Style', 'pushbutton', ...
        'String', 'Mesh', ...
        'Position', [315, 180, 70, 25], ...
        'Callback', @meshbutton_Callback ...
    ); %mesh按钮
    hcontour = uicontrol( ...
        'Style', 'pushbutton', ...
        'String', 'Contour', ...
        'Position', [315, 135, 70, 25], ...
        'Callback', @contourbutton_Callback ...
    ); %contour按钮
    htext  = uicontrol( ...
        'Style', 'text', ...
        'String', 'Select Data', ...
        'Position', [325, 90, 60, 15] ...
    ); %文本提示
    hpopup = uicontrol( ...
        'Style', 'popupmenu', ...
        'String', {'Peaks', 'Membrane', 'Sinc'}, ...
        'Position', [300, 50, 100, 25], ...
        'Callback', @popup_menu_Callback ...
    ); %下拉框
    ha = axes( ...
        'Units', 'pixels', ...
        'Position', [50, 60, 200, 185] ...
    ); %图形区域
    %文字和按钮对齐
    align([hsurf, hmesh, hcontour, htext, hpopup], 'Center', 'None');
    %初始化所有组件
    f.Units = 'normalized';
    ha.Units = 'normalized';
    hsurf.Units = 'normalized';
    hmesh.Units = 'normalized';
    hcontour.Units = 'normalized';
    htext.Units = 'normalized';
    hpopup.Units = 'normalized';
    % 产生数据集
    peaks_data = peaks(35);
    membrane_data = membrane;
    [x, y] = meshgrid(-8:.5:8);
    r = sqrt(x.^2+y.^2) + eps;
    sinc_data = sin(r)./r;
    % 绘制默认数据
    current_data = peaks_data;
    surf(current_data);
    % 将窗口居中
    movegui(f, 'center');
    % 绘制完毕，使窗口可见
    f.Visible = 'on';
    % 所有响应函数
    % 下拉框响应
    function popup_menu_Callback(source, eventdata) 
        % 获取选取值
        str = get(source, 'String');
        val = get(source, 'Value');
        % 切换数据集
        switch str{val};
        case 'Peaks' % 使用Peaks
            current_data = peaks_data;
        case 'Membrane' % 使用Membrane
            current_data = membrane_data;
        case 'Sinc' % 使用Sinc
            current_data = sinc_data;
        end
        % 绘制图表
        surf(current_data);
    end
    % surf按钮响应
    function surfbutton_Callback(source, eventdata)
        % 绘制图表
        surf(current_data);
    end
    % mesh按钮响应
    function meshbutton_Callback(source, eventdata)
        % 绘制图表
        mesh(current_data);
    end
    % contour按钮响应
    function contourbutton_Callback(source, eventdata) 
        % 绘制图表
        contour(current_data);
    end
end